#!/bin/bash
tail -n +2 | cut -f -1 | sort -k 1 | uniq -c | sort -rnk 1 | head -n 11 | rev | cut -d '' -f -1 | rev find -type f -name "*.gif" | cut -d "/" -f 1 | cut -d '.' -f 2- | rev | LC_ALL=C sort -f
